AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lamby WebSocket Demo

Parameters:

  RailsEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production

Globals:

  Function:
    Architectures:
      - arm64
    AutoPublishAlias: live
    DeploymentPreference:
      Type: AllAtOnce
    Environment:
      Variables:
        RAILS_ENV: !Ref RailsEnv
        DATABASE_URL: x-crypteia-ssm:/lamby-ws/env/DATABASE_URL
    Timeout: 30

Resources:

  RailsLambda:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
      DockerTag: web
    Properties:
      FunctionUrlConfig:
        AuthType: NONE
      MemorySize: 1792
      PackageType: Image
      Policies:
        - Statement:
          - Effect: Allow
            Action: ["ssm:Get*", "ssm:Describe*"]
            Resource:
              - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/lamby-ws/env/*

  WSTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
      - AttributeName: scopeID
        KeyType: HASH
      - AttributeName: dataID
        KeyType: RANGE
      AttributeDefinitions:
      - AttributeName: scopeID
        AttributeType: S
      - AttributeName: dataID
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  WSTableConnection:
    Type: AWS::Serverless::Connector
    Properties:
      Source: { Id: RailsLambda }
      Destination: { Id: WSTable }
      Permissions: [Read, Write]

  WSApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref RailsLambda
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.message"

  WSDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - WSConnectRoute
      - WSDefaultRoute
      - WSDisconnectRoute
    Properties:
      ApiId: !Ref WSApi

  WSStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: cable
      DeploymentId: !Ref WSDeployment
      ApiId: !Ref WSApi

  WSPolicy:
    Type: AWS::IAM::Policy
    DependsOn: RailsLambdaRole
    Properties:
      PolicyName: !Sub "${RailsLambda}-ws-policy"
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: ["execute-api:Invoke", "execute-api:ManageConnections"]
            Resource: 
              - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WSApi}/*
      Roles:
        - !Ref RailsLambdaRole

  WSConnectLambda:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
      DockerTag: ws-connect
    Properties:
      MemorySize: 1792
      PackageType: Image
      Role: !GetAtt RailsLambdaRole.Arn
      ImageConfig:
        Command: ["config/environment.LambdaCable.cmd"]
  
  WSConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WSApi
      AuthorizationType: NONE
      RouteKey: "$connect"
      OperationName: WSConnectRoute
      Target: !Sub integrations/${WSConnectIntegration}

  WSConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WSApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WSConnectLambda.Arn}/invocations

  WSConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WSApi
      - WSConnectLambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WSConnectLambda
      Principal: apigateway.amazonaws.com

  WSDefaultLambda:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
      DockerTag: ws-default
    Properties:
      MemorySize: 1792
      PackageType: Image
      Role: !GetAtt RailsLambdaRole.Arn
      ImageConfig:
        Command: ["config/environment.LambdaCable.cmd"]

  WSDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WSApi
      AuthorizationType: NONE
      RouteKey: "$default"
      OperationName: WSDefaultRoute
      Target: !Sub integrations/${WSDefaultIntegration}

  WSDefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WSApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WSDefaultLambda.Arn}/invocations

  WSDefaultPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WSApi
      - WSDefaultLambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WSDefaultLambda
      Principal: apigateway.amazonaws.com

  WSDisconnectLambda:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
      DockerTag: ws-disconnect
    Properties:
      MemorySize: 1792
      PackageType: Image
      Role: !GetAtt RailsLambdaRole.Arn
      ImageConfig:
        Command: ["config/environment.LambdaCable.cmd"]

  WSDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WSApi
      AuthorizationType: NONE
      RouteKey: "$disconnect"
      OperationName: WSDisconnectRoute
      Target: !Sub integrations/${WSDisconnectIntegration}

  WSDisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WSApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WSDisconnectLambda.Arn}/invocations

  WSDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WSApi
      - WSDisconnectLambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WSDisconnectLambda
      Principal: apigateway.amazonaws.com

Outputs:

  RailsLambdaUrl:
    Description: Lambda Function URL
    Value: !GetAtt RailsLambdaUrl.FunctionUrl
