development:
  # adapter: async
  adapter: redis
  url: redis://redis:6379/1

test:
  adapter: test

production:
  adapter: lambda_cable
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: lamby-ws
