default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  host: <%= ENV.fetch("MYSQL_HOST") { "localhost" } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: websocket-demo

test:
  <<: *default
  database: websocket-demo-test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
